### ISSUE TITLE
build rats-tls with DCAP(version 1.14) failure

### ISSUE THREAD

**Issue by liangzhou121** [inclavare-containers/rats-tls#80] opened 2022-07-05 10:38 UTC
Build rats-tls (SGX mode) with DCAP version 1.14 will encounter following error:
/root/zhouliang/rats-tls/src/verifiers/sgx-ecdsa/verify_evidence.c:18:10: fatal error: sgx_dcap_ql_wrapper.h: No such file or directory
 #include <sgx_dcap_ql_wrapper.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/build.make:158: recipe for target 'src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/verify_evidence.c.o' failed
make[2]: *** [src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/verify_evidence.c.o] Error 1
make[2]: Leaving directory '/root/zhouliang/rats-tls/build'
CMakeFiles/Makefile2:676: recipe for target 'src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/all' failed
make[1]: *** [src/verifiers/sgx-ecdsa/CMakeFiles/verifier_sgx_ecdsa.dir/all] Error 2
make[1]: Leaving directory '/root/zhouliang/rats-tls/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jiazhang0** [comment] 2022-07-05 10:51
Caused by `cmake -DRATS_TLS_BUILD_MODE="sgx" -DBUILD_SAMPLES=on -H. -Bbuild`. Only sgx mode has this issue.

**Comment by jiazhang0** [comment] 2022-07-05 11:21
build/src/CMakeFiles/rats_tls.dir/flags.make decides the include dirs.

sgx build mode:
```
C_FLAGS =  -std=gnu11 -fPIC -ggdb -O0    -std=gnu11 -fPIC -ggdb -O0 -m64 -O0 -g -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wredundant-decls -Wstrict-prototypes -Wunsuffixed-float-constants -Wno-implicit-function-declaration -std=c11 -m64 -Wall -nostdinc -ffreestanding -fvisibility=hidden -fpic -fpie -ffunction-sections -fdata-sections -fstack-protector-strong

C_DEFINES = -DSGX

C_INCLUDES = -I/root/zhouliang/rats-tls/src/include -I/root/zhouliang/rats-tls/src/include/rats-tls -I/root/zhouliang/rats-tls/src/include/internal -I/root/zhouliang/rats-tls/src/include/edl -I/root/zhouliang/rats-tls/build/src/sgx/trust -I/root/zhouliang/rats-tls/build/../src/external/sgx-ssl/intel-sgx-ssl/src/intel-sgx-ssl/Linux/package/include -I/root/zhouliang/rats-tls/build/src -I/opt/intel/sgxsdk/include -I/opt/intel/sgxsdk/include/tlibc -I/opt/intel/sgxsdk/include/libcxx 
```

non-sgx build mode:
```
# compile C with /usr/bin/cc
C_FLAGS =  -std=gnu11 -fPIC -ggdb -O0 -fPIC

C_DEFINES = -DHOST -Drats_tls_EXPORTS

C_INCLUDES = -I/root/zhouliang/rats-tls/src/include -I/root/zhouliang/rats-tls/src/include/rats-tls -I/root/zhouliang/rats-tls/src/include/internal
```

sgx mode of course doesn't include standard include search path. This issue could be avoided if not build sgx-ecdsa driver in sgx mode.

**Comment by jiazhang0** [comment] 2022-07-06 05:53
Fixed by https://github.com/inclavare-containers/rats-tls/pull/82

**Closed by jiazhang0** 2022-07-06 05:53 UTC
